### ISSUE TITLE
Herringbone Rack

### ISSUE THREAD

**Issue by keithemery** [chrisspen/gears#3]
I know this isn't exactly an issue.  But would it be possible to ad a herring bone rack?

**Comment by chrisspen** [comment]
I have no personal need for this, but you should be able to do this yourself by using the current rack().

You can make one strip of angled teeth like:

                rack(
                    modul=1,
                    length=length,
                    hoehe=5,
                    width=10,
                    pressure_angle=20,
                    gradient_angle=20
                );

and then mirror it to produce a herringbone. I haven't tested this, so you'd probably have to tweak it to ensure it meshes correctly with a herringbone gear.

**Comment by keithemery** [comment]
Done.
